### ISSUE TITLE
Enable screenshot.js to accept optional query params

### ISSUE THREAD

**Issue by choraria** [choraria/pptr-io#2]
List of configurable query params —

- [ ] width, height & deviceScaleFactor
- [ ] fullPage
- [ ] format/type

etc.

**Comment by deepanshu2506** [comment]
I can work on this please assign it to me.

**Comment by deepanshu2506** [comment]
also can you elaborate a bit on what each option exactly needs to do.

**Comment by deepanshu2506** [comment]
according to my understanding

- there are 2 possibilities for height and width

1.  screenshot the area from from 0,0 to width,height
2. set the viewport width and height 

- fullPage: screenshot the entire page
-deviceScaleFactor: this is set for the viewport
-format/type : the file type of the screenshot as in .jpg , .png, etc.

please correct me if I am wrong anywhere and clarify the usecase for the width/height options

**Comment by choraria** [comment]
Hey @deepanshu2506 👋🏽  thanks for pitching-in. I'm practically thinking about doing something similar for width/height (as well as all the other params) as shown here —
https://apiflash.com/documentation#parameters

Basically need to retrofit them to what I suspect would be the options shown here —
https://github.com/choraria/pptr-io/blob/main/api/screenshot.js#L25-L27
